# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-30 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181129_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approve_comments',
            new_name='approved_comment',
        ),
    ]
